# Generated by Django 3.2.3 on 2021-06-08 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('district_id', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('last_notified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheresmyjab.districts')),
            ],
        ),
    ]
